server:
  port: ${PORT:8080}   

spring:
  application:
    name: voting-system-api-gateway

  cloud:
    gateway:
       
      
eureka:
  client:
    enabled: false   # <<< DESATIVADO para produção no Render
  instance:
    appname: voting-system-api-gateway
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
